final products = [
  {
    'id': '0',
    'title': 'Men\'s Adidas Shoes',
    'price': 44.52,
    'imageUrl': 'assets/images/adidas1.png',
    'company': 'Adidas',
    'sizes': [9, 10, 11, 12],
  },
  {
    'id': '1',
    'title': 'Adidas Yeezy',
    'price': 20.12,
    'imageUrl': 'assets/images/adidas2.png',
    'company': 'Adidas',
    'sizes': [9, 10, 12],
  },
  {
    'id': '2',
    'title': 'Nike Men',
    'price': 28.95,
    'imageUrl': 'assets/images/nike1.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '3',
    'title': 'Jordan Shoes',
    'price': 420.69,
    'imageUrl': 'assets/images/nike2.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '4',
    'title': 'Nike',
    'price': 42.99,
    'imageUrl': 'assets/images/nike5.png',
    'company': 'Nike',
    'sizes': [7, 8, 9, 10],
  },
  {
    'id': '5',
    'title': 'Jordan Shoes',
    'price': 399.99,
    'imageUrl': 'assets/images/nike6.png',
    'company': 'Nike',
    'sizes': [8, 9, 10],
  },
  {
    'id': '6',
    'title': 'Air Max',
    'price': 199.99,
    'imageUrl': 'assets/images/nike7.png',
    'company': 'Nike',
    'sizes': [7, 8, 9, 10],
  },
];
